# Generated by Django 4.2.8 on 2024-02-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='crosslistings',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
    ]
