# Generated by Django 4.2.10 on 2024-04-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compass', '0002_course_crosslistings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='users', to='compass.requirement'),
        ),
    ]
